spring:
  application:
    name: AuthService

  profiles:
    active: local


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

user:
  signup:
    passwordError: "Password must contain upper,lower"